### ISSUE TITLE
Fix issue with relative import

### ISSUE THREAD

**Issue by marceloFA** [marceloFA/pycee2#17]
I'd like to replace all relative imports at ``pycee/``with absolute imports as this is a cleaner approach to imports. The only thing stopping me from doing this is that pytest won't recognize the ``pycee.utils`` module if I do ``from utils import foo`` instead of ``from .utils import foo``

**Comment by LeonardoFurtado** [comment]
We can close this issue? @marceloFA

**Comment by marceloFA** [comment]
Not right now but very soon

**Comment by marceloFA** [comment]
Fixed by #28. See marcelofa@c89ca2c
