### ISSUE TITLE
Choose a open source license

### ISSUE THREAD

**Issue by marceloFA** [marceloFA/pycee2#22]
We still have no license and in order to publish Pycee 2 as a python package and later as a web code editor, we certainly will need one. I've been thinking of the MIT license for this project as it is very simple and permissive but some discussion on this is certainly needed. [This source](https://choosealicense.com/licenses/mit/) has a few relevant information on the MIT license if someone wants to better understand it.

As mentioned by Leonardo, one important consideration is [the license used by PythonBuddy](https://choosealicense.com/licenses/mit/), BSD-3. Their license allows for modification and distribution, which are our expected usage cases of their project, so I think it's fine and won't cause us problems.

**Comment by LeonardoFurtado** [comment]
we need to consider the PythonBuddy and  pycee v1 license to choose a license for this project, because we must avoid license conflicts.

**Comment by ctreude** [comment]
I'd be happy with using MIT. We never chose a licence for Pycee v1, so no constraints from that side.

**Comment by marceloFA** [comment]
Solved by marcelofa@ab5b518
